### ISSUE TITLE
Get the chat text input to be positioned at absolute bottom

### ISSUE THREAD

**Issue by rarebreed** [rarebreed/khadga#30]
I've tried to do the following in the style.css but it didn't work:

```css
.is-bottom {
  position: absolute;
  bottom: 0px;
}
```

But it wasn't working.  I even tried to import bulma.min.css and then do direct classes:

```css
.field.has-addons .is-bottom {
  flex-grow: 1;
  flex-shrink: 1;
  position: absolute;
  bottom: 0px;  
}
```

Neither that, nore making .is-bottom descend directly (ie .field.has-addons.is-bottom) worked.  I think I may need to put the column inside a CSS Grid div.  Then I can just roll my own field.
